todo/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.todo, name='todo'),
    path('view/<int:id>', views.view, name='view'),
    path('create/', views.create, name='create'),
    path('completed/', views.completed, name='completed'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('completed/<int:id>', views.completed_by_id, name='completed_by_id'),
]

todolist_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),  # 我引入我在user內的urls.py
    path('', include('todo.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# user/...
urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logour/', views.user_logout, name='logout')
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# title -str
# text -str(blank = True)
# created -datetime -(auto=True)
# important -bool - (defaullt = False)
# completed -bool - (default = False)


class Todo(models.Model):
    title = models.CharField(max_length=30)
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=True)
    date_completed = models.DateTimeField(blank=True, null=True)
    important = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)

    # Foreignkey外鍵關聯(user_id <=> Todo_id)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title}- {self.user}'

user/models.py
from statistics import mode
import django
from django.db import models
# Create your models here.

todo/forms.py
from django.forms import ModelForm
from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = [
            'title',
            'text',
            'important',
            'completed'
        ]

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserForm(UserCreationForm):
    email = forms.EmailField(required=True, label='信箱：')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

todo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Todo
from .forms import TodoForm
from datetime import datetime
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def completed_by_id(request, id):
    todo = get_object_or_404(Todo, id=id)

    todo.completed = not todo.completed
    # if todo.completed:
    #     todo.completed = False
    # else:
    #     todo.completed = True

    todo.date_completed = datetime.today().strftime(
        '%Y-%m-%d %H:%M:%S') if todo.completed else None
    todo.save()
    return redirect('todo')


def delete(request, id):
    todo = get_object_or_404(Todo, id=id)
    todo.delete()

    return redirect('todo')


@login_required
def completed(request):
    todos = Todo.objects.filter(user=request.user, completed=True)
    return render(request, './todo/completed.html', locals())


@login_required
def create(request):
    form = TodoForm()
    message = ''
    try:
        if request.method == 'POST':
            form = TodoForm(request.POST)
            if form.is_valid():  # form表單是否符合合法(設定標準)
                todo = form.save(commit=False)  # 因沒有user資訊，故先將commit=False先不儲存
                todo.user = request.user
                todo.save()  # 可以將資料儲存到資料庫
                return redirect('todo')
            else:
                message = '新增失敗'
    except Exception as e:
        print(e)
    return render(request, './todo/create.html', locals())


@login_required
def view(request, id):
    # todo = Todo.objects.filter(id=id)
    message = ''
    todo = get_object_or_404(Todo, id=id)
    form = TodoForm(instance=todo)  # 取的表單資訊
    if request.method == 'POST':
        if request.POST.get('delete'):
            todo.delete()
            return redirect('todo')

        if request.POST.get('update'):
            message = '更新失敗'
            try:
                form = TodoForm(request.POST, instance=todo)
                if form.is_valid():
                    todo = form.save(commit=False)
                    todo.date_completed = datetime.today().strftime('%Y-%m-%d %H:%M:%S')\
                        if todo.completed else None
                    todo.save()
                    return redirect('todo')
            except Exception as e:
                print(e)

    return render(request, './todo/view.html', locals())


def todo(request):
    todos = None
    if request.user.is_authenticated:
        todos = Todo.objects.filter(user=request.user)
    print(todos)
    return render(request, './todo/todo.html', locals())

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .forms import CustomUserForm
# Create your views here.

# login


def user_login(request):
    message = ''
    if request.method == "POST":
        if request.POST.get('register'):
            return redirect('register')  # 重新導向register網頁
        if request.POST.get('login'):
            username = request.POST.get('username')
            password = request.POST.get('password')
            if username == '' or password == '':
                message = '帳號跟密碼不能為空'
            else:
                user = authenticate(
                    request, username=username, password=password)

                if not user:
                    message = '帳號或密碼錯誤'
                else:
                    message = '登入成功！！'
                    login(request, user)
                    return redirect('todo')
    return render(request, './user/login.html', locals())


# register model
def user_register(request):
    message = ''
    form = CustomUserForm()
    if request.method == "POST":
        print(request.POST)
        username = request.POST.get('username')  # 取得前端的name
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        email = request.POST.get('email')
        # 密碼問題
        if password1 != password2:
            message = '兩次密碼輸入不同'
        # 密碼過短
        elif len(password1) < 8:
            message = '密碼過短(至少8個字元)'
        else:
            # 帳號重複
            if User.objects.filter(username=username).exists():
                message = 'user重複'
            else:
                user = User.objects.create_user(username=username,
                                                password=password1,
                                                email=email)
                if user is not None:
                    user.save()
                    print('註冊成功！！')
                    login(request, user)
                    return redirect('todo')
    return render(request, './user/register.html', locals())


@login_required
def user_profile(request):
    return render(request, './user/profile.html', locals())


@login_required
def user_logout(request):
    logout(request)

    return redirect('todo')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todolist</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <!-- <link rel="stylesheet" href="../static/css/style.css"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css"
        rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
</head>

<body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'todo' %}"><img src="{% static 'images/coffee-time.png'%}" alt=""
                    width="30px"></a>


            <a id="burger" role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar-links" class="navbar-menu">
            {% if user.is_authenticated %}
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'profile'%}">
                    使用者：{{user.username | upper}}
                </a>

                <a class="navbar-item has-background-warning has-text-danger" href="{% url 'logout'%}">
                    登出
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        功能
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'create' %}">
                            建立todo
                        </a>
                        <a class="navbar-item" href="{% url 'completed' %}">
                            檢視已完成todo
                        </a>
                    </div>
                </div>

            </div>
            {% else %}
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'register' %}">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button has-text-primary" href="{% url 'login' %}">
                            Log in
                        </a>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </nav>
    <section class="hero is-info is-fullheight-with-navbar">
        <div class="hero-body">
            <div class="container">
                {% block content %}


                {% endblock %}
                {% if message %}
                <div class="columns is-centered">
                    <div class="column is-4">
                        <div class="notification is-primary has-text-centered" id="message">
                            <button class="delete"></button>
                            {{ message }}
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
    <script>
        const bugerIcorn = document.querySelector('#burger');
        const navbarmenu = document.querySelector('#navbar-links');

        bugerIcorn.addEventListener("click", () => {
            navbarmenu.classList.toggle("is-active");
        });
    </script>
</body>

</html>

templates/todo/todo.html
{% extends 'base.html' %}{% block content%}
<h1>Todo</h1>
<ul>
    {% for todo in todos %}

    <li>
        <a href="{% url 'view' todo.id %}">
            {{ todo.title }}
            {% if todo.important %}(重要)
            {% endif%}
        </a>
    </li>

    {% endfor %}
</ul>

{% endblock %}

todo/templates/todo/completed.html
{% extends 'base.html' %}{% block content%}
<h1>Todo</h1>
<ul>
    {% for todo in todos %}

    <li>
        <a href="{% url 'view' todo.id %}">
            {{ todo.title }}{% if todo.important %}(重要){% endif%}
        </a>
        -({{ todo.date_completed }})
    </li>

    {% endfor %}
</ul>

{% endblock %}

todo/templates/todo/create.html
{% extends 'base.html' %}{% block content%}
<h1>Create</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">新增</button>
</form>
<p style="color: red;">{{ message }}</p>

{% endblock %}

todo/templates/todo/todo.html
{% extends 'base.html' %}{% block content%}
{% if user.is_authenticated %}
<div class="columns is-centered has-text-centered">
    <div class="column is-size-1">代辦事項</div>
</div>
{% endif %}
{% for todo in todos %}
<div class="columns is-centered">
    <div class="column is-6">
        <div class="card">
            <header class="card-header has-background-grey">
                <p class="card-header-title is-size-4 has-text-grey-lighter">
                    {% if todo.completed %}
                    <s>
                        {{ todo.title }}
                        {% if todo.important %}(重要){% endif%} </s>
                    {% else %}
                    {{ todo.title }}{% if todo.important %}(重要){% endif%}
                    {% endif %}
                    </a>
                </p>
                <button class="card-header-icon" aria-label="more options">
                    <span class="icon">
                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                    </span>
                </button>
            </header>
            <div class="card-content">
                <div class="content">
                    {{ todo.text }}
                </div>
            </div>
            <footer class="card-footer">
                <a href="{% url 'view' todo.id %}" class="card-footer-item">檢視</a>
                <a href="{% url 'completed_by_id' todo.id %}" class="card-footer-item">完成</a>
                <a href="{% url 'delete' todo.id %}" class="card-footer-item">刪除</a>
            </footer>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

todo/templates/todo/view.html
{% extends 'base.html' %}{% block content%}
<div class="columns is-centered has-text-centered">
    <div class="column is-size-1">檢視</div>
</div>
<div class="columns is-centered">
    <div class="column is-4">
        <form action="" method="POST" class="box has-text-centered">
            {% csrf_token %}
            <div class="field">
                <label class="label">標題</label>
                <div class="control">
                    <input class="input has-text-centered" type="text" name="title" value="{{ todo.title }}"
                        id="id_title">
                </div>
            </div>
            <div class="field">
                <label class="label">內文</label>
                <div class="control">
                    <textarea class="textarea" name="text" required id="id_text">{{ todo.text }}</textarea>
                </div>
            </div>
            <div class="field">
                <div class="control has-text-left">
                    <input type="checkbox" name="important" id="id_important" {% if todo.important %} checked
                        {% endif %}>重要
                    <input type="checkbox" name="completed" id="id_completed" {% if todo.completed %} checked
                        {% endif %}>完成
                </div>
            </div>
            <div class="field is-grouped is-grouped-centered">
                <p class="control">
                    <input class="button is-primary" type="submit" name="update" value="更新">
                </p>
                <p class="control">
                    <input class="button is-warning" type="submit" name="delete" value="刪除">
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% block content%}
<div class="columns is-centered has-text-centered">
    <div class="column is-size-1">登入</div>
</div>
<div class="columns is-centered">
    <div class="column is-4">
        <form action="" method="POST" class="box has-text-centered">
            {% csrf_token %}
            <div class="field">
                <label for="username" class="label">帳號</label>
                <div class="control">
                    <input class="input has-text-centered" type="text" name="username" id="username"
                        placeholder="Text input">
                </div>
            </div>
            <div class="field">
                <label for="password" class="label">密碼</label>
                <div class="control">
                    <input class="input has-text-centered" type="password" name="password" id="password"
                        placeholder="Text input">
                </div>
            </div>
            <div class="field is-grouped is-grouped-centered">
                <p class="control">
                    <input class="button is-primary" type="submit" name="login" value="登入">
                </p>
                <p class="control">
                    <input class="button is-warning" type="submit" name="register" value="註冊">
                </p>
                <p class="control">
                    <input class="button is-danger" type="reset" name="reset" value="清除">
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

user/templates/user/profile.html
{% extends 'base.html' %}

{% block content%}
<h1>Profile</h1>
<h1>{{ user.username }}</h1>
<ul>
    <li>信箱：{{ user.email }}</li>
    <li>加入時間：{{ user.date_joined }}</li>
    <li>最後登入時間：{{ user.last_login }}</li>
    {% if user.is_superuser %}
    <li>管理員</li>
    {% endif %}
</ul>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}

{% block content%}
<h1>Register</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">註冊</button>
</form>
<p style="color: red;">{{ message }}</p>
{% endblock %}